CREATE DATABASE IF NOT EXISTS `f40fw2jqiz1m1a0h`;
USE `f40fw2jqiz1m1a0h`;
CREATE TABLE IF NOT EXISTS `burgers` (
    `id` INTEGER PRIMARY KEY AUTO_INCREMENT,
    `burger_name` VARCHAR(24) NOT NULL,
    `devoured` BOOLEAN DEFAULT FALSE
)