CREATE DATABASE IF NOT EXISTS `burgers_db`;
USE `burgers_db`;
CREATE TABLE IF NOT EXISTS `burgers` (
    `id` INTEGER PRIMARY KEY AUTO_INCREMENT,
    `burger_name` VARCHAR(24) NOT NULL,
    `devoured` BOOLEAN DEFAULT FALSE
)